### ISSUE TITLE
Sim-workbench: simulator crashes with json generated from SMK XML and using grow_motti

### ISSUE THREAD

**Issue by Sorvalampi** [menu-hanke/sim-workbench#41]
Sim-workbench: simulator crashes with json generated from SMK XML and using grow_motti

**Comment by Sorvalampi** [comment]
Output file (json as txt) and error messages attached as well as control.yaml as txt.
[Vehmasvuori.txt](https://github.com/menu-hanke/sim-workbench/files/8850724/Vehmasvuori.txt)
[Vehmasvuori_result.txt](https://github.com/menu-hanke/sim-workbench/files/8850726/Vehmasvuori_result.txt)
[control_yaml.txt](https://github.com/menu-hanke/sim-workbench/files/8850731/control_yaml.txt)

**Comment by jpy-luke** [comment]
Please put the error result printout as the description of the issue in the future and the input file as .json instead of .txt, and the control file as .yaml instead of .txt.

**Comment by Sorvalampi** [comment]
@jpy-luke  I have tried. The system says: We dón't support that file type (json)
![image](https://user-images.githubusercontent.com/61448265/172318333-25c18cf1-4b1a-4265-9e7a-eb9acd5cf276.png)

**Comment by dmela** [comment]
@Sorvalampi can you plese verify the this has not yet been addressed and is still valid bug?
