### ISSUE TITLE
grow_motti or pymotti needs to work with None values for properties

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/sim-workbench#44]
This affects at least the `ForestStand.degree_days` value. We use `None` to signify unknown values, for which a default value has not been able to be formulated. pymotti can't handle this via the `MottiGrowthPredictor.dd` property wrapper, but raises Exception about not being able to handle the NoneType. The Exception is understandable, but we need either to

* handle the None value in MottiGrowthPredictor.dd so that it will trigger the usage of pymotti internal temperature sum calculation, or
* handle this in pymotti in some manner, or
* PREFERRED: expose some pymotti functionality that allows us to calculate the temperature sum for a forest stand as a pre-processing step. Perhaps this could be extracted out into the coming domain functions library.

None is a value with significance that can be expected to exist in source data, so please comment on a strategy of how to not fall into this trap with other potential None values in the data.

**Comment by taplem** [comment]
> None is a value with significance that can be expected to exist in source data, so please comment on a strategy of how to not fall into this trap with other potential None values in the data.

In general there's 3 kinds of variables in the `pymotti.Predict` class:
- Variables that must come from the data, ie. motti has no model for them (eg. the heights of trees).
- Variables that may come from the data, or motti may calculate them (eg. temperature sum). Note that this is a pymotti extension, the native version always computes these and won't accept them as input data.
- Variables that are only outputs, ie. pymotti doesn't read them (eg. growth info)

For the first kind we can't really do anything (at least inside pymotti). For the second kind, you can either provide them as proprties like `MottiGrowthPredictor` does, or if you're not sure whether your input data contains them, you can give them as kwargs to the `Predict` class like so:
```python
inputs = {}
if dd is not None:
    inputs["dd"] = dd
growth = MottiGrowthPredictor(**inputs)
```
Some variables are also typed as `Optional`, which means they can be missing. Really there's no general solution though,
this has to be looked at on a per-variable basis.

**Comment by jpy-luke** [comment]
Ok, thank you for explanation. This gives a recipe for handling cases as they emerge. This issue does not need to exist as such anymore, so I'll close it. Let's handle the temperature sum with the preprocessing step approach later.
