### ISSUE TITLE
Save simulator output in a human-readable file

### ISSUE THREAD

**Issue by Sorvalampi** [menu-hanke/sim-workbench#80]
Save simulator output in a human-readable file.

Attached three examples:
1 Schedules with sample trees
[sim_schedules.txt](https://github.com/menu-hanke/sim-workbench/files/8924704/sim_schedules.txt)
2 Schedules with timber volumes as a sum of whole forest stand compartment (m3/ha) (requires timber volume calculation = apteeraus)
[sim_schedules_timber.txt](https://github.com/menu-hanke/sim-workbench/files/8924711/sim_schedules_timber.txt)
3 Full schedules (most human-readable version), practically same as 2 but more readable
[sim_full_schedules.txt](https://github.com/menu-hanke/sim-workbench/files/8924716/sim_full_schedules.txt)

**Comment by dmela** [comment]
For this and #87 create a reader selector function that takes is parametrizable based on CLI flag about the input and output format. You should be able to construct this so that the reader selector is usable in simulator and postprocessing apps. It may be fruitfull to check vmi-data-convertter app entry file for simular solution.

**Comment by dmela** [comment]
If we consider the sim-workbench, as it is now. As a process it would look like this:
preprocess->simulation->postprocess

For example, in the preprocessing step the reference trees are generated from tree stratums.

@Sorvalampi do you think it is necessary to get human-readable output after each indivudal process component? I.e would it be interesting to also get output after the preprocess step?

**Comment by Sorvalampi** [comment]
@dmela: "do you think it is necessary to get human-readable output after each indivudal process component? I.e would it be interesting to also get output after the preprocess step?"
What actually does this pre-process step do?

**Comment by dmela** [comment]
Preprocessing is actually:
- The domain logic from vmi-data-convertter (eg. weibull, etc. tree generation).
- excluding sapling trees, empty stand, zero stem trees
and probably some thing else te become.

You can consider the preprocessing to become the output of vmi-data-convertter. So I believe it is important to get human-readable output as we can then look at how the reference trees are generated from stratums etc.

**Comment by Sorvalampi** [comment]
Absolutely, I agree. @dmela Do you add an issue of that?

**Comment by dmela** [comment]
I'll fix a task. We also have .csv for now these are fine.

**Comment by Sorvalampi** [comment]
Let's further develop this, see issue #147. It's aim is to create a schedulewise text output. To be noticed at least by @dmela and @unie31 .
